name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  JAVA_VERSION: "8"
  JAVA_DISTRIBUTION: "corretto"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Corretto JDK + sbt
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: sbt

      - name: Run tests
        run: sbt test